### ISSUE TITLE
How to place plugin in Homebridge?

### ISSUE THREAD

**Issue by SoullessElbows** [Kwintenvdb/homebridge-vesync-client#2]

**Comment by SoullessElbows** [comment]
@Kwintenvdb How do you import this to Homebridge? Normally it's through NPM.

**Comment by Kwintenvdb** [comment]
Hi there @SoullessElbows, sorry for the late reply.

The plugin is now available via NPM: https://www.npmjs.com/package/homebridge-vesync-client

Note that it currently has limited functionality and is still under development.
