### ISSUE TITLE
Unable to compile plugin

### ISSUE THREAD

**Issue by crospa91** [Kwintenvdb/homebridge-vesync-client#3]
Hi there, 
probably this plugin has been abandoned but I was wondering if you can publish at least a compiled version of this, so we can see how to progress with the development!
I'm unable to compile on my side!

**Comment by Kwintenvdb** [comment]
Hi there. Sorry for the late reply!

I'll update this plugin soon and publish it to NPM, so that you can easily import it into your homebridge setup.

**Comment by crospa91** [comment]
Thanks!!

**Comment by Kwintenvdb** [comment]
Hi @crospa91,

The plugin is now available via NPM: https://www.npmjs.com/package/homebridge-vesync-client
I've always included instructions in the repository's README on how to build the plugin locally.
