### ISSUE TITLE
accessory button does not respond to clicks meant to turn it ON/OFF

### ISSUE THREAD

**Issue by arkaddas** [Kwintenvdb/homebridge-vesync-client#4]
I was trying to setup a Levoit air purifier with Homebridge. It works through Vesync. Homebridge and Vesync plugin installation was smooth and Homebridge was able to detect my Levoit. It also appeared in the Home app on my phone, as a smart plug. The only issue is the device does not seem to receive the switching commands from the phone. From the Homebridge UI - Accessories page, the accessory button does not respond to clicks meant to turn it ON/OFF and remains on OFF.
Edit: From the Homebridge UI - Accessories page, it turns ON momentarily after a deadtime of a few seconds and then turns back OFF.
https://www.reddit.com/r/homebridge/comments/kgfwgg/any_idea_how_to_get_a_leviot_air_purifier_to_be/

**Comment by Kwintenvdb** [comment]
Hi there, sorry for the late reply. 

The plugin is still under development (very slowly) and experimental. However, with some of the latest updates, you should be able to at the very least turn your air purifier on and off using the plugin. Please give it a try.
